### ISSUE TITLE
Distinct or explicitly non-distinct 0 and -0

### ISSUE THREAD

**Issue by ckknight** [tc39/proposal-integer#29]
The similarity or difference between `0n` and `-0n` should be called out in the spec.

**Comment by ljharb** [comment]
Is there any chance we could disallow -0 as an integer?

**Comment by bakkot** [comment]
Strongly support `0n` and `-0n` being the same value (as I believe it is in the current text); agreed that it should be called out somewhere.

@ljharb, could disallow the syntax `-0n`, and _maybe_ should, but of course couldn't disallow `x = 0n; -x;`.

**Comment by ljharb** [comment]
@bakkot sure but couldn't we make `-x` produce `0n`? In other words, literally make "integer negative zero" nonexistent.

**Comment by ckknight** [comment]
I don't think disallowing the syntax `-0n` is necessary, it's simply equivalent to `0n` and code formatters could choose to convert to `0n`.

**Comment by littledan** [comment]
I agree with @ckknight and @bakkot -- we should make `-0n` be `0n`. Note that there is no literal syntax for a negative number--it's unary negation. So `-0n` will evaluate to `0n`.
