### ISSUE TITLE
Wrong length on `Integer#toString`?

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-integer#34]
Why is the length on https://tc39.github.io/proposal-integer/#sec-integer.prototype.tostring 1? The `radix` argument is optional.

I'm aware that `Number.prototype.toString.length` is 1, but this is for legacy reasons, which is why the spec has to explicitly state its length (by the default algorithm, it'd be 0).

**Comment by littledan** [comment]
I think you're right; the length should be 1. I'll write a patch to fix this.
